### ISSUE TITLE
Release 1.0.2 broke my app

### ISSUE THREAD

**Issue by gabzim** [Foxandxss/koa-unless#7]
It took me a while to figure out why exactly my app broke since this is a patch release, I didn't quite suspect this module breaking anything. Here's my stack:

```
"TypeError: Cannot read property 'state' of undefined
    at AuthController.isPublic (/var/app/current/api/auth/auth.controller.js:25:23)
    at matchesCustom (/var/app/current/node_modules/koa-unless/index.js:40:24)
    at /var/app/current/node_modules/koa-unless/index.js:22:9
    at dispatch (/var/app/current/node_modules/koa-compose/index.js:44:32)
    at next (/var/app/current/node_modules/koa-compose/index.js:45:18)
    at /var/app/current/node_modules/koa-router/lib/router.js:326:16
    at dispatch (/var/app/current/node_modules/koa-compose/index.js:44:32)
    at next (/var/app/current/node_modules/koa-compose/index.js:45:18)
    at /var/app/current/api/filter.middleware.js:29:19
    at next (native)
    at /var/app/current/api/filter.middleware.js:7:65
    at __awaiter (/var/app/current/api/filter.middleware.js:3:12)
    at /var/app/current/api/filter.middleware.js:20:16
    at dispatch (/var/app/current/node_modules/koa-compose/index.js:44:32)
    at next (/var/app/current/node_modules/koa-compose/index.js:45:18)
    at /var/app/current/api/users/user.controller.js:52:19
    at next (native)
    at fulfilled (/var/app/current/api/users/user.controller.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)"
```

This should have been a major release. The problem is that the unless function I use:

```
function(ctx) {
        return ctx.state.publicRoute === true;
}
```
Is being passed `undefined` instead of the `ctx`. Will try to troubleshoot and provide better details.

**Comment by brunokrebs** [comment]
`v1.0.5` should solve your issue. Sorry for the problems.
